### ISSUE TITLE
Invalid or expired discord invitation link

### ISSUE THREAD

**Issue by c-nv-s** [Localazy-Community/Awesome-Localazy#1]
the discord invite link at the bottom of your main website is expired. it is the same link as mentioned here: https://discuss.localazy.com/t/discord-server/100

**Comment by neophonic** [comment]
> the discord invite link at the bottom of your main website is expired. It is the same link as mentioned here: https://discuss.localazy.com/t/discord-server/100

Hello there, thanks for the report, sent it for the fix.
